model_name_or_path: Qwen/Qwen2.5-7B-Instruct
tp: 2

k: 
  - 4
n: 4

eval_model: Qwen/Qwen2.5-72B-Instruct
eval_urls:
  - http://172.30.48.95:8000/v1
  - http://172.30.48.139:8000/v1
  - http://172.30.24.41:8000/v1

max_out_len: 8192
temperature: 1.0
top_p: 1.0
top_k: 50
repetition_penalty: 1.0